### PR TITLE
Initialize the rotation estimator pointer in realsense2withIMUDriver constructor

### LINKED ISSUE #35: multianalogsensorserver segsfault if subdevice is set to realsense2withIMU
I tried to run the `realsense2withIMU` by means of the `multianalogsensorserver` this should allow me to read the gyro and the accelerometer provided by the realsense D435i. 

I have the following configuration file stored in `sensors/RealSense_conf.ini`
```ini
device       multipleanalogsensorsserver
subdevice    realsense2withIMU
name         /depthCamera
period       10

[SETTINGS]
depthResolution (640 480)
rgbResolution   (640 480)
framerate       30
enableEmitter   true
alignmentFrame  RGB

[HW_DESCRIPTION]
clipPlanes (0.2 10.0)
```
Then I run the device as
```console
yarpdev --from sensors/RealSense_conf.ini
```
I got the following
```
arpdev --from sensors/RealSense_conf.ini
[DEBUG] |yarp.dev.PolyDriver|multipleanalogsensorsserver| Parameters are (HW_DESCRIPTION (clipPlanes (0.200000000000000011102 10.0))) (SETTINGS (depthResolution (640 480)) (rgbResolution (640 480)) (framerate 30) (enableEmitter true) (alignmentFrame RGB)) (device multipleanalogsensorsserver) (from "sensors/RealSense_conf.ini") (name "/depthCamera") (period 10) (single_threaded 1) (subdevice realsense2withIMU)
[DEBUG] |yarp.dev.PolyDriver|realsense2withIMU| Parameters are (HW_DESCRIPTION (clipPlanes (0.200000000000000011102 10.0))) (SETTINGS (depthResolution (640 480)) (rgbResolution (640 480)) (framerate 30) (enableEmitter true) (alignmentFrame RGB)) (device realsense2withIMU) (from "sensors/RealSense_conf.ini") (name "/depthCamera") (period 10) (single_threaded 1) (subdevice realsense2withIMU)
[WARNING] |yarp.device.realsense2withIMU| This software module is experimental.
[WARNING] |yarp.device.realsense2withIMU| It is provided with uncomplete documentation and it may be modified/renamed/removed without any notice.
[INFO] |yarp.device.realsense2| Sensor warm-up...
[INFO] |yarp.device.realsense2| Device ready!
[INFO] |yarp.device.realsense2| Device consists of 3 sensors. More infos using --verbose option
[INFO] |yarp.dev.PolyDriver|realsense2withIMU| Created device <realsense2withIMU>. See C++ class realsense2withIMUDriver for documentation.
[INFO] |yarp.os.Port|/depthCamera/measures:o| Port /depthCamera/measures:o active at tcp://10.240.9.195:10009/
[INFO] |yarp.os.Port|/depthCamera/rpc:o| Port /depthCamera/rpc:o active at tcp://10.240.9.195:10010/
[INFO] |yarp.device.multipleanalogsensorsserver| Subdevice "realsense2withIMU" successfully configured and attached.
[INFO] |yarp.dev.PolyDriver|multipleanalogsensorsserver| Created wrapper <multipleanalogsensorsserver>. See C++ class MultipleAnalogSensorsServer for documentation.
[DEBUG] |yarp.dev.Drivers|multipleanalogsensorsserver| ===============================================================
[DEBUG] |yarp.dev.Drivers|multipleanalogsensorsserver| == Options checked by device:
[DEBUG] |yarp.dev.Drivers|multipleanalogsensorsserver| ==
[DEBUG] |yarp.dev.Drivers|multipleanalogsensorsserver| device=multipleanalogsensorsserver
[DEBUG] |yarp.dev.Drivers|multipleanalogsensorsserver| id [multipleanalogsensorsserver]
[DEBUG] |yarp.dev.Drivers|multipleanalogsensorsserver|     Id assigned to this device
[DEBUG] |yarp.dev.Drivers|multipleanalogsensorsserver| ==
[DEBUG] |yarp.dev.Drivers|multipleanalogsensorsserver| ===============================================================
[INFO] |yarp.os.Port|/depthCamera/quit| Port /depthCamera/quit active at tcp://10.240.9.195:10008/
[INFO] |yarp.dev.Drivers|multipleanalogsensorsserver| device active in background...
Segmentation fault (core dumped)
```

I debug the code using `gdb` and I notice that the code crashes at this line 

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2withIMUDriver.cpp#L517

Indeed the pointer is not allocated 

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2withIMUDriver.cpp#L230-L234

I will provide a PR to fixes the issue cc @traversaro

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This fixes #35, moreover, I also wrote the documentation for the RealSense D435i in the README

cc @traversaro

### CODE REVIEW

**Review by Nicogene — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
@GiulioRomualdi do you expect more fixes? Because it seems that we have several changes that would need a release, but if you have more fixes that you expect to do we can wait.

**Comment by GiulioRomualdi** [comment]
I just realize that with the documentation I wrote, I cannot get the output of the camera but just a port named `/depthCamera/measures:o` where I found the outcome of the imu.

I don't know how can I run two devices (`multipleanalogsensorsserver` and `RGBDSensorWrapper`) connected to the same subdevice (`realsense2withIMU`)

**Comment by Nicogene** [comment]
> I just realize that with the documentation I wrote, I cannot get the output of the camera but just a port named `/depthCamera/measures:o` where I found the outcome of the imu.
> 
> I don't know how can I run two devices (`multipleanalogsensorsserver` and `RGBDSensorWrapper`) connected to the same subdevice (`realsense2withIMU`)

Using `yarpdev` as deployer I think is impossible to have two `nws` but it should work with `yarprobotinterface`

**Comment by GiulioRomualdi** [comment]
Hi @Nicogene thank you 😄 , I'm trying to write an `xml` file for a self-contained robot interface, I let you know.

**Comment by GiulioRomualdi** [comment]
This `xml` file allows me to get the camera along with the gyro and accelerometer

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE robot PUBLIC "-//YARP//DTD yarprobotinterface 3.0//EN" "http://www.yarp.it/DTD/yarprobotinterfaceV3.0.dtd">
<robot name="realsense" build=0 portprefix="/depthCamera">

  <device type="realsense2withIMU" name="camera">
    <group name="SETTINGS">
      <param name="depthResolution">(640 480)</param>
      <param name="rgbResolution">(640 480)</param>
      <param name="framerate">30</param>
      <param name="enableEmitter">true</param>
      <param name="alignmentFrame">RGB</param>
    </group>

    <group name="HW_DESCRIPTION">
      <param name="clipPlanes">(0.2 10.0)</param>
    </group>
  </device>

  <device type="RGBDSensorWrapper" name="rgbd_sensor_wrapper">
    <param name="period">20</param>
    <param name="name">/depthCamera</param>

    <action phase="startup" level="5" type="attach">
      <paramlist name="networks">
        <elem name="camera">camera</elem>
      </paramlist>
    </action>
    <action phase="shutdown" level="5" type="detach"/>
  </device>

  <device type="multipleanalogsensorsserver" name="imu_sensor_wrapper">
    <param name="period">10</param>
    <param name="name">/depthCamera_imu</param>

    <action phase="startup" level="5" type="attach">
      <paramlist name="networks">
        <elem name="camera">camera</elem>
      </paramlist>
    </action>
    <action phase="shutdown" level="5" type="detach"/>
  </device>

</robot>
```
however, I noticed that when `multipleanalogsensorsserver` is attached to the device the framerate is not respected. As you can see in the following image:
image

On the other hand, when `multipleanalogsensorsserver` does not run (and attached) I'm able to stream the videos at 30fps 

image

Do you have any idea why this is happening?

**Comment by Nicogene** [comment]
Not sure if it is the same problem but, we experienced low fps passing from `RGBDSensorWrapper` (deprecated) to `rgbdSensor_nws_yarp` but we didn't have the chance to investigate it.

Could you try with `rgbdSensor_nws_yarp` ?

**Comment by GiulioRomualdi** [comment]
I think the problem is a bit more complex. `multipleanalogsensorsserver` and `RGBDSensorWrapper` are attached to the same device (`realsense2withIMU`) This means that these two threads (`multipleanalogsensorsserver` and `RGBDSensorWrapper`) will call the associated functions of to get the imu measurements and the images. 
As you can notice here, every time a gyro or an accelerometer is requested `wait_for_frames()` method is called

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2withIMUDriver.cpp#L369-L372

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2withIMUDriver.cpp#L421-L424

The same happens when an image is requested 

https://github.com/robotology/yarp-device-realsense2/blob/d4da73fa2336c40d7d479bb8ee87c317f2128c9b/src/devices/realsense2/realsense2Driver.cpp#L1028-L1031

`wait_for_frames` blocks the execution of the device. 

I think this is happening with this configuration because we have two sources of data handled by two different threads (`multipleanalogsensorsserver` and `RGBDSensorWrapper`). 

A possible solution (is to call `wait_for_frames()` in the `run()` of the `realsense2Driver` device and then the get methods just read the buffers without calling `wait_for_frames()`

**Comment by traversaro** [comment]
> A possible solution (is to call `wait_for_frames()` in the `run()` of the `realsense2Driver` device and then the get methods just read the buffers without calling `wait_for_frames()`

Yes, this is tipically how YARP devices are implemented. Either you have a thread that blocks to wait for data, or you use callbacks to populate some internal buffers. Not sure if this is problematic for example for the image, as it means that we have some additional copy of the image.

**Comment by traversaro** [comment]
fyi @Nicogene @randaz81

**Comment by traversaro** [comment]
> Not sure if this is problematic for example for the image, as it means that we have some additional copy of the image.

Looking at the code it seems that data is always copied to the `rs2::frameset` data structure every time `wait_for_frames()` is called, so I do not think that calling it in a thread would change the efficiency.

**Comment by Nicogene** [comment]
It is something that should be tested, but the solution provided by @GiulioRomualdi seems ok 👍🏻

**Comment by traversaro** [comment]
What do you think @GiulioRomualdi @Nicogene , should we merge?

**Comment by Nicogene** [comment]
> What do you think @GiulioRomualdi @Nicogene , should we merge? I do not think there is an high possibility of regression here as this was fixing something that was not working fine.

I would merge as well 👍🏻

**Comment by GiulioRomualdi** [comment]
As you prefer, but keep in mind that enabling the imu will slow down the rate at which the images arrive. So in case someone needs the IMu I would suggest using the [ros2 node](https://github.com/IntelRealSense/realsense-ros)

**Comment by traversaro** [comment]
> As you prefer, but keep in mind that enabling the imu will slow down the rate at which the images arrive. So in case someone needs the IMu I would suggest using the [ros2 node](https://github.com/IntelRealSense/realsense-ros)

I agree, but this happens also before this PR, right?

**Comment by GiulioRomualdi** [comment]
> so before this PR, right?

Before the PR the device segfaults if attached to a multipleanalogsensorserver

**Comment by traversaro** [comment]
Good point, so basically with this modification the method is not segfaulting anymore, but the performances are really bad, right? So probably it may be better to have a clear error, rather then a behaviour that seems ok but it actually bad. At this point, let's close this PR and open an issue, people interested in this feature may resurrect this PR if interested in this.

**Comment by traversaro** [comment]
> Good point, so basically with this modification the method is not segfaulting anymore, but the performances are really bad, right? So probably it may be better to have a clear error, rather then a behaviour that seems ok but it actually bad. At this point, let's close this PR and open an issue, people interested in this feature may resurrect this PR if interested in this.

Issue in https://github.com/robotology/yarp-device-realsense2/issues/37, for the time being we close the PR.

**Pull request closed without merging**
