### PR TITLE
Move realsense2 documentation from YARP as README.md

### PR DESCRIPTION
**Pull request by drdanz**
Original author: @aikolina

As discussed in robotology/yarp#2371

### CODE REVIEW

**Comment by drdanz** [comment]
CC @traversaro

**Comment by Nicogene** [comment]
In this way we lost the doxy documentation am I right?

In particular, I think that this table is very important to have it in the documentation:

https://github.com/robotology/yarp-device-realsense2/blob/33a3ed204dac65bab2b7cafe183c6983a0cfdb5d/src/devices/realsense2/realsense2Driver.h#L39-L79

**Comment by Nicogene** [comment]
PS: I think that we have also to setup the code-ownership as was inside yarp in order to be automatically mentioned as reviewers

**Comment by drdanz** [comment]
The generated page is this: http://yarp.it/classrealsense2Driver.html (the link will disappear when we remove the driver for YARP)
We can either run doxygen in this repository as well, or port it to markdown (in the README.md or in a separate file)

Anyway, the important thing right now is that the documentation is in the same repository as the code...

**Comment by drdanz** [comment]
> PS: I think that we have also to setup the code-ownership as was inside yarp in order to be automatically mentioned as reviewers

@Nicogene You won the ownership! :smile:
Here's the [CODEOWNERS](https://github.com/robotology/yarp-device-realsense2/blob/master/.github/CODEOWNERS) file

**Pull request merged**
