### PR TITLE
Document installation from conda-forge

### PR DESCRIPTION
**Pull request by traversaro**
We recently added the `yarp-device-realsense2` package to conda-forge (see https://github.com/conda-forge/staged-recipes/pull/28542 and https://github.com/conda-forge/yarp-device-realsense2-feedstock/), so I think it could be a good idea to document this way of installing the repo.

### CODE REVIEW

**Comment by traversaro** [comment]
@apicis can you check if the documentation make sense after this PR? Thanks!

**Comment by apicis** [comment]
Documentation makes sense to me. Thanks!

**Comment by traversaro** [comment]
By the way, I just tested this on ergocub-head with JetPack 5.1.2 (L4T 35.4.1) and it is working as expected, including the CUDA acceleration!

**Review by Nicogene — COMMENTED** [review]
Maybe it misses a reference of what conda/pixi is?

**Comment by traversaro** [comment]
> Maybe it misses a reference of what conda/pixi is?

I added some links, do you think it is sufficient or you think it is better something else?

**Review by Nicogene — APPROVED** [review]
The links are fine!

**Pull request merged**
